---

#######################################
# Setup Kubernetes cluster internal DNS
#######################################

# Expects kubectl being configured on the local machine
# using kubectl.yaml playbook

- hosts: 127.0.0.1
  connection: local

  tasks:

  - name: Create local temp directory
    local_action:
      module: command mktemp -d "{{ lookup('env', 'TMPDIR') | default('/tmp/') }}ansible.XXXX"
    register: mktemp_out

  # TODO Should create skydns only if not presente yet

  - name: Create skydns service configuration
    template:
      src: "{{ playbook_dir }}/templates/kubernetes/skydns-svc.yaml.j2"
      dest: "{{ mktemp_out.stdout }}/skydns-svc.yaml"

  - name: Create skydns replication controller configuration
    template:
      src: "{{ playbook_dir }}/templates/kubernetes/skydns-rc.yaml.j2"
      dest: "{{ mktemp_out.stdout }}/skydns-rc.yaml"

  - name: Create skydns service
    shell: "kubectl create -f {{ mktemp_out.stdout }}/skydns-svc.yaml"

  # TODO Should verify service is running

  - name: Delete skydns replication controller (if any)
    shell: "kubectl --namespace=kube-system delete rc kube-dns-v18"
    ignore_errors: yes

  - name: Create skydns replication controller
    shell: "kubectl create -f {{ mktemp_out.stdout }}/skydns-rc.yaml"

  # TODO Should verify pods are running
