---

#######################################
# Deploy and expose Nginx service
#######################################

# Expects kubectl being configured on the local machine
# using kubectl.yaml playbook


- hosts: 127.0.0.1
  connection: local

  tasks:

  - name: Launch 3 ngix pods
    command: "kubectl run nginx --image=nginx --port=80 --replicas=3"

  - name: Expose nginx
    command: "kubectl expose deployment nginx --type NodePort"

  - debug: msg="hello"

  - name: Get exposed port
    command: "kubectl get svc nginx --output=jsonpath='{range .spec.ports[0]}{.nodePort}'"
    register: result
  - set_fact:
      node_port: "{{ result.stdout }}"

  - debug: msg="Exposed port {{ node_port }}"
